src/main/java/cd/forexy/web/ContratBean.java
package cd.forexy.web;

import cd.forexy.domain.*;
import cd.forexy.domain.security.UserEntity;
import cd.forexy.service.AgenceService;
import cd.forexy.service.ContratAttachmentService;
import cd.forexy.service.ContratService;
import cd.forexy.service.ParametreService;
import cd.forexy.service.security.SecurityWrapper;
import cd.forexy.service.security.UserService;
import cd.forexy.print.HeaderFooterPageEvent;
import cd.forexy.web.generic.GenericLazyDataModel;
import cd.forexy.web.util.MessageFactory;

import java.awt.image.BufferedImage;
import java.io.*;
import java.time.LocalDate;
import java.util.*;
import java.util.List;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.activation.MimetypesFileTypeMap;
import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;
import javax.imageio.ImageIO;
import javax.imageio.ImageWriter;
import javax.imageio.stream.ImageOutputStream;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.OptimisticLockException;
import javax.persistence.PersistenceException;
import javax.servlet.http.HttpServletResponse;


import com.itextpdf.text.*;
import com.itextpdf.text.pdf.PdfWriter;
import org.apache.commons.io.IOUtils;
import org.imgscalr.Scalr;
import org.imgscalr.Scalr.Method;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.primefaces.model.UploadedFile;

@Named("contratBean")
@ViewScoped
public class ContratBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private static final Logger logger = Logger.getLogger(ContratBean.class.getName());

    private GenericLazyDataModel<ContratEntity> lazyModel;

    private ContratEntity contrat;

    private List<ContratAttachment> contratAttachments;

    @Inject
    private ContratService contratService;

    @Inject
    private ContratAttachmentService contratAttachmentService;

    UploadedFile uploadedImage;
    byte[] uploadedImageContents;

    @Inject
    private AgenceService agenceService;

    @Inject
    private UserService userService;
    @Inject
    private ParametreService parametreService;


    private List<AgenceEntity> allAgencesList;

    private List<UserEntity> allUsersList;

    private List<AgenceEntity> allAgence2sList;
    private UserEntity connectedUser;


    public void prepareNewContrat() {
        reset();
        this.contrat = new ContratEntity();
        // set any default values now, if you need
        // Example: this.contrat.setAnything("test");
    }

    public GenericLazyDataModel<ContratEntity> getLazyModel() {
        if (this.lazyModel == null) {
            this.lazyModel = new GenericLazyDataModel<>(contratService);
        }
        return this.lazyModel;
    }

    public void setConnectedUser(UserEntity connectedUser) {
        this.connectedUser = connectedUser;
    }

    public String persist() {

        if (contrat.getId() == null && !isPermitted("contrat:create")) {
            return "accessDenied";
        } else if (contrat.getId() != null && !isPermitted(contrat, "contrat:update")) {
            return "accessDenied";
        }

        String message;

        try {

            if (this.uploadedImage != null) {
                try {

                    BufferedImage image;
                    try (InputStream in = new ByteArrayInputStream(uploadedImageContents)) {
                        image = ImageIO.read(in);
                    }
                    image = Scalr.resize(image, Method.BALANCED, 300);

                    ByteArrayOutputStream baos = new ByteArrayOutputStream();
                    ImageOutputStream imageOS = ImageIO.createImageOutputStream(baos);
                    Iterator<ImageWriter> imageWriters = ImageIO.getImageWritersByMIMEType(
                            uploadedImage.getContentType());
                    ImageWriter imageWriter = (ImageWriter) imageWriters.next();
                    imageWriter.setOutput(imageOS);
                    imageWriter.write(image);

                    baos.close();
                    imageOS.close();

                    logger.log(Level.INFO, "Resized uploaded image from {0} to {1}", new Object[]{uploadedImageContents.length, baos.toByteArray().length});

                    ContratImage contratImage = new ContratImage();
                    contratImage.setContent(baos.toByteArray());
                    contrat.setImage(contratImage);
                } catch (Exception e) {
                    FacesMessage facesMessage = MessageFactory.getMessage(
                            "message_upload_exception");
                    FacesContext.getCurrentInstance().addMessage(null, facesMessage);
                    FacesContext.getCurrentInstance().validationFailed();
                    return null;
                }
            }

            if (contrat.getId() != null) {
                contrat = contratService.update(contrat);
                message = "message_successfully_updated";
            } else {
                AgenceEntity agence = this.getConnectedUser().getAgence();
                contrat.setAgence(agence);
                contrat.setUser(this.getConnectedUser());
                contrat.setDate(new Date());
                contrat.setStatut(ContratStatut.ACTIF);
                contrat.setDateEcheance1(addedMonths(contrat.getDate(), 4));
                contrat.setDateEcheance2(addedMonths(contrat.getDate(), 8));
                contrat.setDateEcheance3(addedMonths(contrat.getDate(), 12));
                System.out.println("agence = " + agence);
                long maxContractNumerForAgence = contratService.getMaxContractNumerForAgence(agence);
                contrat.setContratNumber((int) (maxContractNumerForAgence + 1));

                contrat.setContratID(String.format("%04d", contrat.getContratNumber()) + "/INV/" + agence.getAgenceID().toUpperCase() + "/" + LocalDate.now().getYear());
                contrat.setRecuID("RECU-" + contrat.getContratID());
                contrat = contratService.save(contrat);
                message = "message_successfully_created";
            }
        } catch (OptimisticLockException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_optimistic_locking_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        } catch (PersistenceException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_save_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }

        FacesMessage facesMessage = MessageFactory.getMessage(message);
        FacesContext.getCurrentInstance().addMessage(null, facesMessage);

        return null;
    }

    public String delete() {

        if (!isPermitted(contrat, "contrat:delete")) {
            return "accessDenied";
        }

        String message;

        try {
            contratService.delete(contrat);
            message = "message_successfully_deleted";
            reset();
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_delete_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
        FacesContext.getCurrentInstance().addMessage(null, MessageFactory.getMessage(message));

        return null;
    }

    public void onDialogOpen(ContratEntity contrat) {
        reset();
        this.contrat = contrat;
    }

    public void reset() {
        contrat = null;

        contratAttachments = null;

        allAgencesList = null;

        allUsersList = null;

        allAgence2sList = null;

        uploadedImage = null;
        uploadedImageContents = null;

    }

    // Get a List of all agence
    public List<AgenceEntity> getAgences() {
        if (this.allAgencesList == null) {
            this.allAgencesList = agenceService.findAllAgenceEntities();
        }
        return this.allAgencesList;
    }

    // Update agence of the current contrat
    public void updateAgence(AgenceEntity agence) {
        this.contrat.setAgence(agence);
        // Maybe we just created and assigned a new agence. So reset the allAgenceList.
        allAgencesList = null;
    }

    // Get a List of all user
    public List<UserEntity> getUsers() {
        if (this.allUsersList == null) {
            this.allUsersList = userService.findAllUserEntities();
        }
        return this.allUsersList;
    }

    // Update user of the current contrat
    public void updateUser(UserEntity user) {
        this.contrat.setUser(user);
        // Maybe we just created and assigned a new user. So reset the allUserList.
        allUsersList = null;
    }

    // Get a List of all agence2
    public List<AgenceEntity> getAgence2s() {
        if (this.allAgence2sList == null) {
            this.allAgence2sList = agenceService.findAllAgenceEntities();
        }
        return this.allAgence2sList;
    }

    // Update agence2 of the current contrat
    public void updateAgence2(AgenceEntity agence) {
        this.contrat.setAgence2(agence);
        // Maybe we just created and assigned a new agence. So reset the allAgence2List.
        allAgence2sList = null;
    }

    public SelectItem[] getCiviliteSelectItems() {
        SelectItem[] items = new SelectItem[ContratCivilite.values().length];

        int i = 0;

src/main/webapp/pages/contrat/contratAttachmentsInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
    xmlns:f="http://xmlns.jcp.org/jsf/core"
    xmlns:h="http://xmlns.jcp.org/jsf/html"
    xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
    xmlns:p="http://primefaces.org/ui">

    <p:outputPanel styleClass="ui-fluid" rendered="#{not contratBean.isPermitted(contratBean.contrat, 'contrat:read')}">
        <h:outputText value="#{messages.access_denied}" />
    </p:outputPanel>
    
    <p:outputPanel styleClass="ui-fluid" rendered="#{contratBean.isPermitted(contratBean.contrat, 'contrat:read')}">
        <h:form enctype="multipart/form-data" rendered="#{contratBean.isPermitted(contratBean.contrat, 'contrat:update')}">
          <h:outputText value="#{messages.label_upload_files}" />
          <p:fileUpload immediate="true"
              fileUploadListener="#{contratBean.handleAttachmentUpload}"
              update=":contratAttachmentsPanel" style="overflow:auto;height:120px;width:620px" fileLimit="1" />
        </h:form>
        <h:form>
          <p:dataTable scrollable="true" scrollHeight="270" resizableColumns="true"
              rendered="#{not empty contratBean.contratAttachments}" style="width:620px"
              var="attachment" value="#{contratBean.contratAttachments}">
            <f:facet name="header"><h:outputText value="#{messages.attachments_uploaded}: " /></f:facet>
            <p:column headerText="#{messages.attachment_filename}" width="500">
                <p:commandButton ajax="false" title=" " ariaLabel=" " label=" " styleClass="btn btn-sm btn-success fa fa-download">
                    <p:fileDownload value="#{contratBean.getAttachmentStreamedContent(attachment)}" />
                </p:commandButton>
                <h:outputText value="#{attachment.fileName}" />
            </p:column>
            <p:column width="40">
                <p:commandButton icon="ui-icon-close" style="background-color: red; color: white" title="#{messages.label_delete}" rendered="#{contratBean.isPermitted(contratBean.contrat, 'contrat:update')}"
                    action="#{contratBean.deleteAttachment(attachment)}" update="@form :growlForm:growl" />
            </p:column>
          </p:dataTable>
        </h:form>
    </p:outputPanel>

</html>

src/main/webapp/pages/contrat/contratEditInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

<div class="ui-g ui-fluid">
    <div class="ui-g-6 ui-sm-12">
        <div class="ui-material no-float mt-0 ">
            <h:outputLabel value="#{messages.field_label_contrat_nom}:" for="nomEditInput"/>
            <h:inputText value="#{contratBean.contrat.nom}" id="nomEditInput"
                         class="form-control form-control-sm form-control-border"
                         label="#{messages.field_label_contrat_nom}"/>
            <p:message for="nomEditInput" display="text"/>
        </div>
    </div>
    <div class="ui-g-6 ui-sm-12">
        <div class="ui-material no-float mt-0 ">
            <h:outputLabel value="#{messages.field_label_contrat_postNom}:" for="postNomEditInput"/>
            <h:inputText value="#{contratBean.contrat.postNom}" id="postNomEditInput"
                         class="form-control form-control-sm form-control-border"
                         label="#{messages.field_label_contrat_postNom}"/>
            <p:message for="postNomEditInput" display="text"/>
        </div>
    </div>
    <div class="ui-g-6 ui-sm-12">
        <div class="ui-material no-float mt-0 ">
            <h:outputLabel value="#{messages.field_label_contrat_prenom}:" for="prenomEditInput"/>
            <h:inputText value="#{contratBean.contrat.prenom}" id="prenomEditInput"
                         class="form-control form-control-sm form-control-border"
                         label="#{messages.field_label_contrat_prenom}"/>
            <p:message for="prenomEditInput" display="text"/>
        </div>
    </div>
    <div class="ui-g-6 ui-sm-12">
        <div class="form-group form-group-sm">
            <h:outputLabel value="#{messages.field_label_contrat_civilite}:" for="civiliteSelect"/>
            <h:selectOneMenu value="#{contratBean.contrat.civilite}" converter="omnifaces.GenericEnumConverter"
                             class="form-control form-control-sm form-control-border" id="civiliteSelect">
                <f:selectItem noSelectionOption="true" itemLabel=""/>
                <f:selectItems value="#{contratBean.civiliteSelectItems}"/>
            </h:selectOneMenu>
            <p:message for="civiliteSelect" display="text"/>
        </div>
    </div>
    <div class="ui-g-6 ui-sm-12">
        <div class="ui-material no-float mt-0 ">
            <h:outputLabel value="#{messages.field_label_contrat_adresse}:" for="adresseEditInput"/>
            <h:inputText value="#{contratBean.contrat.adresse}" id="adresseEditInput"
                         class="form-control form-control-sm form-control-border"
                         label="#{messages.field_label_contrat_adresse}"/>
            <p:message for="adresseEditInput" display="text"/>
        </div>
    </div>
    <div class="ui-g-6 ui-sm-12">
        <div class="ui-material no-float mt-0 ">
            <h:outputLabel value="#{messages.field_label_contrat_piece}:" for="pieceSelect"/>
            <h:selectOneMenu value="#{contratBean.contrat.piece}" converter="omnifaces.GenericEnumConverter"
                             class="form-control form-control-sm form-control-border" id="pieceSelect">
                <f:selectItem noSelectionOption="true" itemLabel=""/>
                <f:selectItems value="#{contratBean.pieceSelectItems}"/>
            </h:selectOneMenu>
            <p:message for="pieceSelect" display="text"/>
        </div>
    </div>
    <div class="ui-g-6 ui-sm-12">
        <div class="ui-material no-float mt-0 ">
            <h:outputLabel value="#{messages.field_label_contrat_telephone}:" for="telephoneEditInput"/>
            <h:inputText value="#{contratBean.contrat.telephone}" id="telephoneEditInput"
                         class="form-control form-control-sm form-control-border"
                         label="#{messages.field_label_contrat_telephone}"/>
            <p:message for="telephoneEditInput" display="text"/>
        </div>
    </div>
    <div class="ui-g-6 ui-sm-12">
        <div class="ui-material no-float mt-0 ">
            <h:outputLabel value="#{messages.field_label_contrat_email}:" for="emailEditInput"/>
            <h:inputText value="#{contratBean.contrat.email}" id="emailEditInput"
                         class="form-control form-control-sm form-control-border"
                         label="#{messages.field_label_contrat_email}"/>
            <p:message for="emailEditInput" display="text"/>
        </div>
    </div>
    <div class="ui-g-6 ui-sm-12">
        <div class="ui-material no-float mt-0 ">
            <h:outputLabel value="#{messages.field_label_contrat_montant}:" for="montantEditInput"/>
            <h:inputText value="#{contratBean.contrat.montant}" id="montantEditInput"
                         label="#{messages.field_label_contrat_montant}"
                         class="form-control form-control-sm form-control-border"
                         validatorMessage="Le montant doit supérieur ou égal à 300 USD">
                <f:convertNumber/>
                <f:validateDoubleRange minimum="300" for="montantEditInput"/>
            </h:inputText>
            <p:message for="montantEditInput" display="text"/>
        </div>
    </div>
    <div class="ui-g-6 ui-sm-12">
        <div class="ui-material no-float mt-0 ">
            <h:outputLabel value="#{messages.field_label_contrat_bordereauID}:" for="bordereauIDEditInput"/>
            <h:inputText value="#{contratBean.contrat.bordereauID}" id="bordereauIDEditInput"
                         class="form-control form-control-sm form-control-border"
                         label="#{messages.field_label_contrat_bordereauID}"/>
            <p:message for="bordereauIDEditInput" display="text"/>
        </div>
    </div>

</div>
</html>

src/main/webapp/pages/contrat/contratViewInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

    <p:outputPanel styleClass="ui-fluid" rendered="#{not contratBean.isPermitted(contratBean.contrat, 'contrat:read')}">
        <h:outputText value="#{messages.access_denied}" />
    </p:outputPanel>

    
    <h:panelGrid columns="2" styleClass="dialog" columnClasses="col1,col2" rendered="#{contratBean.isPermitted(contratBean.contrat, 'contrat:read')}">

        <h:outputText value="#{messages.field_label_contrat_nom}:" />
        <h:outputText value="#{contratBean.contrat.nom} #{contratBean.contrat.postNom} #{contratBean.contrat.prenom}" />

        <h:outputText value="#{messages.field_label_contrat_piece}:" />
        <h:outputText value="#{contratBean.getLabelForPiece(contratBean.contrat.piece)}" />

        <h:outputText value="#{messages.field_label_contrat_montant}:" />
        <h:outputText value="#{contratBean.contrat.montant} $" ><f:convertNumber /></h:outputText>

        <h:outputText value="#{messages.field_label_contrat_bordereauID}:" />
        <h:outputText value="#{contratBean.contrat.bordereauID}" />

        <h:outputText value="#{messages.field_label_contrat_recuID}:" />
        <h:outputText value="#{contratBean.contrat.recuID}" />

        <h:outputText value="#{messages.field_label_contrat_date}:" />
        <h:outputText value="#{contratBean.contrat.date}" ><f:convertDateTime pattern="dd/MM/yyyy" /></h:outputText>

        <h:outputText value="#{messages.field_label_contrat_adresse}:" />
        <h:outputText value="#{contratBean.contrat.adresse}" />

        <h:outputText value="#{messages.field_label_contrat_telephone}:" />
        <h:outputText value="#{contratBean.contrat.telephone}" />

        <h:outputText value="#{messages.field_label_contrat_email}:" />
        <h:outputText value="#{contratBean.contrat.email}" />

        <h:outputText value="#{messages.field_label_contrat_contratID}:" />
        <h:outputText value="#{contratBean.contrat.contratID}" />


        <h:outputText value="#{messages.audit_created}:" />
        <h:panelGroup>
            <h:outputText value="#{contratBean.contrat.createdAt}"><f:convertDateTime type="both" /></h:outputText>
            <h:outputText value=", #{contratBean.contrat.createdBy}"/>
        </h:panelGroup>
        
        <h:outputText value="#{messages.audit_modified}:" />
        <h:panelGroup>
            <h:outputText value="#{contratBean.contrat.modifiedAt}"><f:convertDateTime type="both" /></h:outputText>
            <h:outputText value=", #{contratBean.contrat.modifiedBy}"/>
        </h:panelGroup>
        
    </h:panelGrid>
</html>