src/main/java/cd/forexy/web/AgenceBean.java
package cd.forexy.web;

import cd.forexy.domain.AgenceEntity;
import cd.forexy.domain.AgenceStatut;
import cd.forexy.service.AgenceService;
import cd.forexy.service.security.SecurityWrapper;
import cd.forexy.web.util.MessageFactory;

import java.io.Serializable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.OptimisticLockException;
import javax.persistence.PersistenceException;

@Named("agenceBean")
@ViewScoped
public class AgenceBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private static final Logger logger = Logger.getLogger(AgenceBean.class.getName());
    
    private List<AgenceEntity> agenceList;

    private AgenceEntity agence;
    
    @Inject
    private AgenceService agenceService;
    
    public void prepareNewAgence() {
        reset();
        this.agence = new AgenceEntity();
        // set any default values now, if you need
        // Example: this.agence.setAnything("test");
    }

    public String persist() {

        if (agence.getId() == null && !isPermitted("agence:create")) {
            return "accessDenied";
        } else if (agence.getId() != null && !isPermitted(agence, "agence:update")) {
            return "accessDenied";
        }
        
        String message;
        
        try {
            
            if (agence.getId() != null) {
                agence = agenceService.update(agence);
                message = "message_successfully_updated";
            } else {
                agence.setStatut(AgenceStatut.ACTIF);
                agence = agenceService.save(agence);
                message = "message_successfully_created";
            }
        } catch (OptimisticLockException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_optimistic_locking_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        } catch (PersistenceException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_save_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
        
        agenceList = null;

        FacesMessage facesMessage = MessageFactory.getMessage(message);
        FacesContext.getCurrentInstance().addMessage(null, facesMessage);
        
        return null;
    }
    
    public String delete() {
        
        if (!isPermitted(agence, "agence:delete")) {
            return "accessDenied";
        }
        
        String message;
        
        try {
            agenceService.delete(agence);
            message = "message_successfully_deleted";
            reset();
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_delete_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
        FacesContext.getCurrentInstance().addMessage(null, MessageFactory.getMessage(message));
        
        return null;
    }
    
    public void onDialogOpen(AgenceEntity agence) {
        reset();
        this.agence = agence;
    }
    
    public void reset() {
        agence = null;
        agenceList = null;
        
    }

    public SelectItem[] getStatutSelectItems() {
        SelectItem[] items = new SelectItem[AgenceStatut.values().length];

        int i = 0;
        for (AgenceStatut statut : AgenceStatut.values()) {
            items[i++] = new SelectItem(statut, getLabelForStatut(statut));
        }
        return items;
    }
    
    public String getLabelForStatut(AgenceStatut value) {
        if (value == null) {
            return "";
        }
        String label = MessageFactory.getMessageString(
                "enum_label_agence_statut_" + value);
        return label == null? value.toString() : label;
    }
    
    public AgenceEntity getAgence() {
        // Need to check for null, because some strange behaviour of f:viewParam
                // Sometimes it is setting to null
        if (this.agence == null) {
            prepareNewAgence();
        }
        return this.agence;
    }
    
    public void setAgence(AgenceEntity agence) {
            if (agence != null) {
        this.agence = agence;
            }
    }
    
    public List<AgenceEntity> getAgenceList() {
        if (agenceList == null) {
            agenceList = agenceService.findAllAgenceEntities();
        }
        return agenceList;
    }

    public void setAgenceList(List<AgenceEntity> agenceList) {
        this.agenceList = agenceList;
    }
    
    public boolean isPermitted(String permission) {
        return SecurityWrapper.isPermitted(permission);
    }

    public boolean isPermitted(AgenceEntity agence, String permission) {
        
        return SecurityWrapper.isPermitted(permission);
        
    }
    public long countAllEntries() {
        return agenceService.countAllEntries();
    }

    
}

src/main/webapp/pages/agence/agence.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">
<ui:composition template="/templates/template.xhtml">
    <ui:define name="content">
        <div class="card elevation-2">
            <div class="card-header">
                <h5 class="card-title"></h5>
                <div class="card-body p-0">
                    <div class="table-responsive">
                        <h:form prependId="false" id="agenceDataForm"
                                onkeypress="if (event.keyCode == 13) {return false; }">

                            <p:dataTable id="agenceTable"
                                         class="no-border table table-hover table-striped table-sm table-responsive table-bg"
                                         value="#{agenceBean.agenceList}" var="agence"
                                         resizableColumns="true" paginator="true"
                                         paginatorTemplate=" {CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                         rowsPerPageTemplate="5,10,25,50" rows="10" draggableColumns="true"
                                         paginatorPosition="bottom" widgetVar="agenceTable"
                                         emptyMessage="#{messages.label_no_records_found}"
                                         reflow="true">

                                <f:facet name="header">
                                    Agences
                                </f:facet>

                                <p:column headerText="#{messages.field_label_agence_nom}" sortBy="#{agence.nom}" width="30"
                                          >

                                    <h:outputText value="#{agence.nom}"/>
                                </p:column>

                                <p:column headerText="#{messages.field_label_agence_idNat}" width="30" sortBy="#{agence.idNat}"
                                          >

                                    <h:outputText value="#{agence.idNat}"/>
                                </p:column>

                                <p:column headerText="#{messages.field_label_agence_rcCM}" width="30" sortBy="#{agence.rcCM}"
                                          >

                                    <h:outputText value="#{agence.rcCM}"/>
                                </p:column>

                                <p:column headerText="#{messages.field_label_agence_telephone}" width="30"
                                          sortBy="#{agence.telephone}" >

                                    <h:outputText value="#{agence.telephone}"/>
                                </p:column>

                                <p:column headerText="#{messages.field_label_agence_email}" sortBy="#{agence.email}" width="50"
                                          >

                                    <h:outputText value="#{agence.email}"/>
                                </p:column>

                                <p:column headerText="#{messages.field_label_agence_adresse}" width="30" sortBy="#{agence.adresse}"
                                          >

                                    <h:outputText value="#{agence.adresse}"/>
                                </p:column>

                                <p:column headerText="#{messages.field_label_agence_agenceID}" width="30"
                                          sortBy="#{agence.agenceID}" >

                                    <h:outputText value="#{agence.agenceID}"/>
                                </p:column>

                                <p:column headerText="#{messages.field_label_agence_statut}" width="30"
                                          sortBy="#{agence.statut}" >

                                    <h:outputText value="#{agenceBean.getLabelForStatut(agence.statut)}"/>
                                </p:column>

                                <p:column styleClass="action-column" headerText="#{messages.table_actions_column}"
                                          width="60" exportable="false">

                                    <p:commandButton icon="ui-icon-zoomin" update=":viewAgenceDialog"
                                                     oncomplete="PF('viewAgenceDialogWidget').show()" value="Voir" style="background-color: #17A2B4"
                                                     title="#{messages.label_view}">
                                        <f:setPropertyActionListener value="#{agence}" target="#{agenceBean.agence}"/>
                                    </p:commandButton>

                                    <p:commandButton icon="ui-icon-pencil" update=":editAgenceDialog"
                                                     resetValues="true" value="Editer" style="background-color: #28a745"
                                                     rendered="#{agenceBean.isPermitted(agence, 'agence:update')}"
                                                     action="#{agenceBean.onDialogOpen(agence)}"
                                                     oncomplete="PF('editAgenceDialogWidget').show()"
                                                     title="#{messages.label_edit}">
                                    </p:commandButton>

                                    <p:commandButton icon="ui-icon-close" style="background-color: red;color: white" value="Effacer"
                                                     rendered="#{agenceBean.isPermitted(agence, 'agence:delete')}"
                                                     oncomplete="PF('deleteAgenceDialogWidget').show()"
                                                     title="#{messages.label_delete}">
                                        <f:setPropertyActionListener value="#{agence}"
                                                                     target="#{agenceBean.agence}"/>
                                    </p:commandButton>

                                </p:column>
                                <f:facet name="footer">
                                    <p:commandButton value="#{messages.create_new_agence}" icon="ui-icon-plusthick"
                                                     action="#{agenceBean.prepareNewAgence()}"
                                                     resetValues="true" update=":editAgenceDialog"
                                                     oncomplete="PF('editAgenceDialogWidget').show()"
                                                     rendered="#{agenceBean.isPermitted('agence:create')}"
                                                     style="float:right"/>
                                    <p:spacer height="30px"/>

                                </f:facet>

                            </p:dataTable>

                        </h:form>
                    </div>
                </div>
            </div>
        </div>

        <p:confirmDialog id="deleteAgenceDialog" widgetVar="deleteAgenceDialogWidget"
                         rendered="#{agenceBean.isPermitted(agenceBean.agence, 'agence:delete')}"
                         header="#{messages.label_confirm_deletion}"
                         severity="alarm">
            <f:facet name="message"><h:outputText value="#{messages.label_delete_record}" escape="false"/></f:facet>
            <p:outputPanel>
                <h:form>
                    <div style="text-align: center; margin:10px">
                        <p:commandButton value="#{messages.label_yes}" action="#{agenceBean.delete}"
                                         update=":agenceDataForm :growlForm:growl"
                                         oncomplete="PF('deleteAgenceDialogWidget').hide()"/>
                        <p:commandButton value="#{messages.label_no}" onclick="PF('deleteAgenceDialogWidget').hide()"
                                         type="button"/>
                    </div>
                </h:form>
            </p:outputPanel>
        </p:confirmDialog>

        <p:dialog dynamic="true" id="editAgenceDialog" header="#{messages.label_agence_caption}"
                 width="400px" modal="true" widgetVar="editAgenceDialogWidget" maximizable="true">
            <p:ajax event="close" listener="#{agenceBean.reset}"/>
            <h:form id="editAgenceForm">
                <p:outputPanel id="agenceEditPanel">
                    <ui:include src="/pages/agence/agenceEditInclude.xhtml"/>
                    <div style="text-align: center; margin:10px">
                        <p:commandButton value="#{messages.label_save}"
                                         icon="ui-icon-disk" action="#{agenceBean.persist}"
                                         update=":editAgenceForm:agenceEditPanel :agenceDataForm :growlForm:growl"
                                         oncomplete="if(!args.validationFailed) PF('editAgenceDialogWidget').hide()"/>
                        <p:commandButton value="#{messages.label_close}" icon="ui-icon-close" style="background-color: red;color: white"
                                         onclick="PF('editAgenceDialogWidget').hide()" type="button"/>
                    </div>
                </p:outputPanel>
            </h:form>
        </p:dialog>

        <p:dialog dynamic="true" id="viewAgenceDialog" header="#{messages.label_agence_caption}" modal="true"
                  widgetVar="viewAgenceDialogWidget" maximizable="true">
            <p:ajax event="close" listener="#{agenceBean.reset}"/>
            <h:form id="viewAgenceForm">
                <ui:include src="/pages/agence/agenceViewInclude.xhtml"/>
                <div style="text-align: center; margin:10px">
                    <p:commandButton value="#{messages.label_close}" icon="ui-icon-close" style="background-color: red;color: white"
                                     onclick="PF('viewAgenceDialogWidget').hide()" type="button"/>
                </div>
            </h:form>
        </p:dialog>

    </ui:define>
</ui:composition>
</html>

src/main/webapp/pages/agence/agenceEditInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

<ui:remove>
    <p:outputPanel styleClass="ui-fluid">

        <p:panelGrid columns="3" columnClasses="ui-grid-col-4,ui-grid-col-6,ui-grid-col-2" layout="grid"
                     style="max-width:400px">

            <h:outputLabel value="#{messages.field_label_agence_nom}:" for="nomEditInput"/>
            <p:inputText value="#{agenceBean.agence.nom}" id="nomEditInput"
                         label="#{messages.field_label_agence_nom}"/>
            <p:message for="nomEditInput" display="text"/>

            <h:outputLabel value="#{messages.field_label_agence_idNat}:" for="idNatEditInput"/>
            <p:inputText value="#{agenceBean.agence.idNat}" id="idNatEditInput"
                         label="#{messages.field_label_agence_idNat}"/>
            <p:message for="idNatEditInput" display="text"/>

            <h:outputLabel value="#{messages.field_label_agence_rcCM}:" for="rcCMEditInput"/>
            <p:inputText value="#{agenceBean.agence.rcCM}" id="rcCMEditInput"
                         label="#{messages.field_label_agence_rcCM}"/>
            <p:message for="rcCMEditInput" display="text"/>

            <h:outputLabel value="#{messages.field_label_agence_telephone}:" for="telephoneEditInput"/>
            <p:inputText value="#{agenceBean.agence.telephone}" id="telephoneEditInput"
                         label="#{messages.field_label_agence_telephone}"/>
            <p:message for="telephoneEditInput" display="text"/>

            <h:outputLabel value="#{messages.field_label_agence_email}:" for="emailEditInput"/>
            <p:inputText value="#{agenceBean.agence.email}" id="emailEditInput"
                         label="#{messages.field_label_agence_email}"/>
            <p:message for="emailEditInput" display="text"/>

            <h:outputLabel value="#{messages.field_label_agence_adresse}:" for="adresseEditInput"/>
            <p:inputText value="#{agenceBean.agence.adresse}" id="adresseEditInput"
                         label="#{messages.field_label_agence_adresse}"/>
            <p:message for="adresseEditInput" display="text"/>

            <h:outputLabel value="#{messages.field_label_agence_agenceID}:" for="agenceIDEditInput"/>
            <p:inputText value="#{agenceBean.agence.agenceID}" id="agenceIDEditInput"
                         label="#{messages.field_label_agence_agenceID}"/>
            <p:message for="agenceIDEditInput" display="text"/>

            <h:outputLabel value="#{messages.field_label_agence_statut}:" for="statutSelect"/>
            <p:selectOneMenu value="#{agenceBean.agence.statut}" converter="omnifaces.GenericEnumConverter"
                             id="statutSelect">
                <f:selectItem noSelectionOption="true" itemLabel=""/>
                <f:selectItems value="#{agenceBean.statutSelectItems}"/>
            </p:selectOneMenu>
            <p:message for="statutSelect" display="text"/>

        </p:panelGrid>

    </p:outputPanel>
</ui:remove>
<div class="ui-g ui-fluid">
    <div class="ui-g-6 ui-sm-12">
        <div class="ui-material no-float mt-0 ">
            <h:outputLabel value="#{messages.field_label_agence_agenceID}:" for="agenceIDEditInput"/>
            <h:inputText value="#{agenceBean.agence.agenceID}" id="agenceIDEditInput"
                         class="form-control form-control-sm form-control-border"
                         label="#{messages.field_label_agence_agenceID}"/>
            <p:message for="agenceIDEditInput" display="text"/>
        </div>
    </div>
    <div class="ui-g-6 ui-sm-12">
        <div class="ui-material no-float mt-0 ">
            <h:outputLabel value="#{messages.field_label_agence_nom}:" for="nomEditInput"/>
            <h:inputText value="#{agenceBean.agence.nom}" id="nomEditInput"
                         class="form-control form-control-sm form-control-border"
                         label="#{messages.field_label_agence_nom}"/>
            <p:message for="nomEditInput" display="text"/>
        </div>
    </div>

    <div class="ui-g-6 ui-sm-12">
        <div class="ui-material no-float mt-0 ">
            <h:outputLabel value="#{messages.field_label_agence_idNat}:" for="idNatEditInput"/>
            <h:inputText value="#{agenceBean.agence.idNat}" id="idNatEditInput"
                         class="form-control form-control-sm form-control-border"
                         label="#{messages.field_label_agence_idNat}"/>
            <p:message for="idNatEditInput" display="text"/>
        </div>
    </div>
    <div class="ui-g-6 ui-sm-12">
        <div class="ui-material no-float mt-0 ">
            <h:outputLabel value="#{messages.field_label_agence_rcCM}:" for="rcCMEditInput"/>
            <h:inputText value="#{agenceBean.agence.rcCM}" id="rcCMEditInput"
                         class="form-control form-control-sm form-control-border"
                         label="#{messages.field_label_agence_rcCM}"/>
            <p:message for="rcCMEditInput" display="text"/>
        </div>
    </div>

    <div class="ui-g-6 ui-sm-12">
        <div class="ui-material no-float mt-0 ">
            <h:outputLabel value="#{messages.field_label_agence_telephone}:" for="telephoneEditInput"/>
            <h:inputText value="#{agenceBean.agence.telephone}" id="telephoneEditInput"
                         class="form-control form-control-sm form-control-border"
                         label="#{messages.field_label_agence_telephone}"/>
            <p:message for="telephoneEditInput" display="text"/>
        </div>
    </div>
    <div class="ui-g-6 ui-sm-12">
        <div class="ui-material no-float mt-0 ">
            <h:outputLabel value="#{messages.field_label_agence_email}:" for="emailEditInput"/>
            <h:inputText value="#{agenceBean.agence.email}" id="emailEditInput"
                         class="form-control form-control-sm form-control-border"
                         label="#{messages.field_label_agence_email}"/>
            <p:message for="emailEditInput" display="text"/>
        </div>
    </div>
    <div class="ui-g-6 ui-sm-12">
        <div class="ui-material no-float mt-0 ">

            <h:outputLabel value="#{messages.field_label_agence_province}:" for="provinceEditInput"/>
            <h:inputText value="#{agenceBean.agence.province}" id="provinceEditInput"
                         class="form-control form-control-sm form-control-border"
                         label="#{messages.field_label_agence_province}"/>
            <p:message for="provinceEditInput" display="text"/>
        </div>
    </div>

    <div class="ui-g-6 ui-sm-12">
        <div class="ui-material no-float mt-0 ">
            <h:outputLabel value="#{messages.field_label_agence_ville}:" for="villeEditInput"/>
            <h:inputText value="#{agenceBean.agence.ville}" id="villeEditInput"
                         class="form-control form-control-sm form-control-border"
                         label="#{messages.field_label_agence_adresse}"/>
            <p:message for="villeEditInput" display="text"/>
        </div>
    </div>

    <div class="ui-g-6 ui-sm-12">
        <div class="ui-material no-float mt-0 ">
            <h:outputLabel value="#{messages.field_label_agence_avenue}:" for="avenueEditInput"/>
            <h:inputText value="#{agenceBean.agence.avenue}" id="avenueEditInput"
                         class="form-control form-control-sm form-control-border"
                         label="#{messages.field_label_agence_avenue}"/>
            <p:message for="avenueEditInput" display="text"/>
        </div>
    </div>


    <!--    <div class="ui-g-6 ui-sm-12">-->
    <!--        <div class="ui-material no-float mt-0 ">-->
    <!--            <h:outputLabel value="#{messages.field_label_agence_adresse}:" for="adresseEditInput"/>-->
    <!--            <h:inputText value="#{agenceBean.agence.adresse}" id="adresseEditInput"-->
    <!--                         class="form-control form-control-sm form-control-border"-->
    <!--                         label="#{messages.field_label_agence_adresse}"/>-->
    <!--            <p:message for="adresseEditInput" display="text"/>-->
    <!--        </div>-->
    <!--    </div>-->
    <!--    -->
    <div class="ui-g-6 ui-sm-12">
        <div class="ui-material no-float mt-0 ">
            <h:outputLabel value="#{messages.field_label_agence_statut}:" for="statutSelect"/>
            <h:selectOneMenu value="#{agenceBean.agence.statut}"
                             class="form-control form-control-sm form-control-border"
                             converter="omnifaces.GenericEnumConverter"
                             id="statutSelect">
                <f:selectItem noSelectionOption="true" itemLabel=""/>
                <f:selectItems value="#{agenceBean.statutSelectItems}"/>
            </h:selectOneMenu>
            <p:message for="statutSelect" display="text"/>
        </div>
    </div>
</div>
</html>

src/main/webapp/pages/agence/agenceViewInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

    <p:outputPanel styleClass="ui-fluid" rendered="#{not agenceBean.isPermitted(agenceBean.agence, 'agence:read')}">
        <h:outputText value="#{messages.access_denied}" />
    </p:outputPanel>
    
    <h:panelGrid columns="2" styleClass="dialog" columnClasses="col1,col2" rendered="#{agenceBean.isPermitted(agenceBean.agence, 'agence:read')}">
        
        <h:outputText value="#{messages.field_label_agence_nom}:" />
        <h:outputText value="#{agenceBean.agence.nom}" />

        <h:outputText value="#{messages.field_label_agence_idNat}:" />
        <h:outputText value="#{agenceBean.agence.idNat}" />

        <h:outputText value="#{messages.field_label_agence_rcCM}:" />
        <h:outputText value="#{agenceBean.agence.rcCM}" />

        <h:outputText value="#{messages.field_label_agence_telephone}:" />
        <h:outputText value="#{agenceBean.agence.telephone}" />

        <h:outputText value="#{messages.field_label_agence_email}:" />
        <h:outputText value="#{agenceBean.agence.email}" />

        <h:outputText value="#{messages.field_label_agence_adresse}:" />
        <h:outputText value="#{agenceBean.agence.adresse}" />

        <h:outputText value="#{messages.field_label_agence_agenceID}:" />
        <h:outputText value="#{agenceBean.agence.agenceID}" />

        <h:outputText value="#{messages.field_label_agence_statut}:" />
        <h:outputText value="#{agenceBean.getLabelForStatut(agenceBean.agence.statut)}" />

    </h:panelGrid>
</html>