src/main/java/cd/forexy/domain/MouvementType.java
package cd.forexy.domain;

public enum MouvementType {
    
    ENTREE, SORTIE;
}

src/main/java/cd/forexy/web/MouvementBean.java
package cd.forexy.web;

import cd.forexy.domain.AgenceEntity;
import cd.forexy.domain.MouvementEntity;
import cd.forexy.domain.MouvementType;
import cd.forexy.domain.security.UserEntity;
import cd.forexy.service.AgenceService;
import cd.forexy.service.MouvementService;
import cd.forexy.service.security.SecurityWrapper;
import cd.forexy.service.security.UserService;
import cd.forexy.web.util.MessageFactory;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.OptimisticLockException;
import javax.persistence.PersistenceException;

@Named("mouvementBean")
@ViewScoped
public class MouvementBean implements Serializable {

    private static final long serialVersionUID = 1L;

    private static final Logger logger = Logger.getLogger(MouvementBean.class.getName());

    private List<MouvementEntity> mouvementList;

    private MouvementEntity mouvement;

    @Inject
    private MouvementService mouvementService;

    @Inject
    private UserService userService;

    @Inject
    private AgenceService agenceService;

    private List<UserEntity> allUsersList;

    private List<AgenceEntity> allAgencesList;
    private UserEntity connectedUser;

    public UserEntity getConnectedUser() {
        if (connectedUser == null) {
            connectedUser = userService.findUserByUsername(SecurityWrapper.getUsername());
        }
        return connectedUser;
    }

    public void prepareNewMouvement() {
        reset();
        this.mouvement = new MouvementEntity();
        // set any default values now, if you need
        // Example: this.mouvement.setAnything("test");
    }

    public String persist() {

        if (mouvement.getId() == null && !isPermitted("mouvement:create")) {
            return "accessDenied";
        } else if (mouvement.getId() != null && !isPermitted(mouvement, "mouvement:update")) {
            return "accessDenied";
        }

        String message;

        try {

            if (mouvement.getId() != null) {
                mouvement = mouvementService.update(mouvement);
                message = "message_successfully_updated";
            } else {
                mouvement.setDate(new Date());
                mouvement.setAgence(this.getConnectedUser().getAgence());
                mouvement = mouvementService.save(mouvement);
                message = "message_successfully_created";
            }
        } catch (OptimisticLockException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_optimistic_locking_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        } catch (PersistenceException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_save_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }

        mouvementList = null;

        FacesMessage facesMessage = MessageFactory.getMessage(message);
        FacesContext.getCurrentInstance().addMessage(null, facesMessage);

        return null;
    }

    public String delete() {

        if (!isPermitted(mouvement, "mouvement:delete")) {
            return "accessDenied";
        }

        String message;

        try {
            mouvementService.delete(mouvement);
            message = "message_successfully_deleted";
            reset();
        } catch (Exception e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_delete_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }
        FacesContext.getCurrentInstance().addMessage(null, MessageFactory.getMessage(message));

        return null;
    }

    public void onDialogOpen(MouvementEntity mouvement) {
        reset();
        this.mouvement = mouvement;
    }

    public void reset() {
        mouvement = null;
        mouvementList = null;

        allUsersList = null;

        allAgencesList = null;

    }

    // Get a List of all user
    public List<UserEntity> getUsers() {
        if (this.allUsersList == null) {
            this.allUsersList = userService.findAllUserEntities();
        }
        return this.allUsersList;
    }

    // Update user of the current mouvement
    public void updateUser(UserEntity user) {
        this.mouvement.setUser(user);
        // Maybe we just created and assigned a new user. So reset the allUserList.
        allUsersList = null;
    }

    // Get a List of all agence
    public List<AgenceEntity> getAgences() {
        if (this.allAgencesList == null) {
            this.allAgencesList = agenceService.findAllAgenceEntities();
        }
        return this.allAgencesList;
    }

    // Update agence of the current mouvement
    public void updateAgence(AgenceEntity agence) {
        this.mouvement.setAgence(agence);
        // Maybe we just created and assigned a new agence. So reset the allAgenceList.
        allAgencesList = null;
    }

    public SelectItem[] getTypeSelectItems() {
        SelectItem[] items = new SelectItem[MouvementType.values().length];

        int i = 0;
        for (MouvementType type : MouvementType.values()) {
            items[i++] = new SelectItem(type, getLabelForType(type));
        }
        return items;
    }

    public String getLabelForType(MouvementType value) {
        if (value == null) {
            return "";
        }
        String label = MessageFactory.getMessageString(
                "enum_label_mouvement_type_" + value);
        return label == null ? value.toString() : label;
    }

    public MouvementEntity getMouvement() {
        // Need to check for null, because some strange behaviour of f:viewParam
        // Sometimes it is setting to null
        if (this.mouvement == null) {
            prepareNewMouvement();
        }
        return this.mouvement;
    }

    public void setMouvement(MouvementEntity mouvement) {
        if (mouvement != null) {
            this.mouvement = mouvement;
        }
    }

    public List<MouvementEntity> getMouvementList() {
        if (mouvementList == null) {
            mouvementList = mouvementService.findAllMouvementEntities();
        }
        return mouvementList;
    }

    public void setMouvementList(List<MouvementEntity> mouvementList) {
        this.mouvementList = mouvementList;
    }

    public boolean isPermitted(String permission) {
        return SecurityWrapper.isPermitted(permission);
    }

    public boolean isPermitted(MouvementEntity mouvement, String permission) {

        return SecurityWrapper.isPermitted(permission);

    }

}

src/main/webapp/pages/mouvement/mouvement.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">
<ui:composition template="/templates/template.xhtml">
    <ui:define name="content">
        <div class="card elevation-2">
            <div class="card-header">


                <div class="card-body p-0">
                    <div class="table-responsive">
                        <h:form prependId="false" id="mouvementDataForm"
                                onkeypress="if (event.keyCode == 13) {return false; }">

                            <p:dataTable id="mouvementTable" tableStyle="table-layout:auto"
                                         class="table table-hover table-striped table-sm table-responsive table-bg no-border"
                                         value="#{mouvementBean.findMouvementsByAgence()}" var="mouvement"
                                         resizableColumns="true" paginator="true"
                                         paginatorTemplate=" {CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                                         rowsPerPageTemplate="5,10,25,50" rows="10" draggableColumns="true"
                                         paginatorPosition="bottom" widgetVar="mouvementTable"
                                         emptyMessage="#{messages.label_no_records_found}"
                                         reflow="true">

                                <f:facet name="header">
                                   Mouvements
                                </f:facet>
                                <p:column  headerText="#{messages.field_label_mouvement_user}" sortBy="#{mouvement.user.username}" width="30"
                                          >
                                    <h:outputText value="#{mouvement.user.username}"/>
                                </p:column>

                                <p:column  headerText="Visiteur" sortBy="#{mouvement.visiteur}" width="30"
                                         >
                                    <h:outputText value="#{mouvement.visiteur}"/>
                                </p:column>

                                <p:column  headerText="#{messages.field_label_mouvement_date}" sortBy="#{mouvement.date}" width="30"
                                         >
                                    <h:outputText value="#{mouvement.date}"><f:convertDateTime/>
                                        <f:convertDateTime pattern="dd/MM/yyyy HH:mm"/>
                                    </h:outputText>
                                </p:column>

                                <p:column  headerText="#{messages.field_label_mouvement_motif}" width="30"
                                          sortBy="#{mouvement.motif}"
                                         >
                                    <h:outputText value="#{mouvement.motif}"/>
                                </p:column>

                                <p:column  headerText="#{messages.field_label_mouvement_type}" width="30"
                                          sortBy="#{mouvement.type}" >
                                    <h:outputText value="#{mouvementBean.getLabelForType(mouvement.type)}"/>
                                </p:column>



                                <p:column styleClass="action-column" headerText="#{messages.table_actions_column}"
                                          width="60"
                                          exportable="false">

                                    <p:commandButton class="btn btn-info" icon="ui-icon-zoomin" value="Voir" style="background-color: #17A2B4" update=":viewMouvementDialog"
                                                     oncomplete="PF('viewMouvementDialogWidget').show()"
                                                     title="#{messages.label_view}">
                                        <f:setPropertyActionListener value="#{mouvement}"
                                                                     target="#{mouvementBean.mouvement}"/>
                                    </p:commandButton>

                                    <p:commandButton class="btn btn-success" value="Editer" style="background-color: #28a745" icon="ui-icon-pencil" update=":editMouvementDialog"
                                                     resetValues="true"
                                                     rendered="#{mouvementBean.isPermitted(mouvement, 'mouvement:update')}"
                                                     action="#{mouvementBean.onDialogOpen(mouvement)}"
                                                     oncomplete="PF('editMouvementDialogWidget').show()"
                                                     title="#{messages.label_edit}">
                                    </p:commandButton>

                                    <p:commandButton icon="ui-icon-close" style="background-color: red;color: white"
                                                     rendered="#{mouvementBean.isPermitted(mouvement, 'mouvement:delete')}"
                                                     oncomplete="PF('deleteMouvementDialogWidget').show()"
                                                     title="#{messages.label_delete}">
                                        <f:setPropertyActionListener value="#{mouvement}"
                                                                     target="#{mouvementBean.mouvement}"/>
                                    </p:commandButton>

                                </p:column>
                                <f:facet name="footer">
                                    <p:commandButton value="#{messages.create_new_mouvement}" icon="ui-icon-plusthick"
                                                     action="#{mouvementBean.prepareNewMouvement()}"
                                                     resetValues="true" update=":editMouvementDialog"
                                                     oncomplete="PF('editMouvementDialogWidget').show()"
                                                     rendered="#{mouvementBean.isPermitted('mouvement:create')}"
                                                     style="float:right"/>
                                    <p:spacer height="30px"></p:spacer>
                                </f:facet>

                            </p:dataTable>

                        </h:form>
                    </div>
                </div>


            </div>
        </div>


        <p:confirmDialog id="deleteMouvementDialog" widgetVar="deleteMouvementDialogWidget"
                         rendered="#{mouvementBean.isPermitted(mouvementBean.mouvement, 'mouvement:delete')}"
                         header="#{messages.label_confirm_deletion}"
                         severity="alarm">
            <f:facet name="message"><h:outputText value="#{messages.label_delete_record}" escape="false"/></f:facet>
            <p:outputPanel>
                <h:form>
                    <div style="text-align: center; margin:10px">
                        <p:commandButton value="#{messages.label_yes}" action="#{mouvementBean.delete}"
                                         update=":mouvementDataForm :growlForm:growl"
                                         oncomplete="PF('deleteMouvementDialogWidget').hide()"/>
                        <p:commandButton value="#{messages.label_no}" onclick="PF('deleteMouvementDialogWidget').hide()"
                                         type="button"/>
                    </div>
                </h:form>
            </p:outputPanel>
        </p:confirmDialog>

        <p:dialog dynamic="true" id="editMouvementDialog" header="#{messages.label_mouvement_caption}"
                  modal="true" widgetVar="editMouvementDialogWidget" maximizable="true">
            <p:ajax event="close" listener="#{mouvementBean.reset}"/>
            <h:form id="editMouvementForm">
                <p:outputPanel id="mouvementEditPanel">
                    <ui:include src="/pages/mouvement/mouvementEditInclude.xhtml"/>
                    <div style="text-align: center; margin:10px">
                        <p:commandButton value="#{messages.label_save}"
                                         icon="ui-icon-disk" action="#{mouvementBean.persist}"
                                         update=":mouvementDataForm :editMouvementForm:mouvementEditPanel :growlForm:growl"
                                         oncomplete="if(!args.validationFailed) PF('editMouvementDialogWidget').hide()"/>
                        <p:commandButton value="#{messages.label_close}" icon="ui-icon-close" style="background-color: red;color: white"
                                         onclick="PF('editMouvementDialogWidget').hide()" type="button"/>
                    </div>
                </p:outputPanel>
            </h:form>
        </p:dialog>

        <p:dialog dynamic="true" id="viewMouvementDialog" header="#{messages.label_mouvement_caption}" modal="true"
                  widgetVar="viewMouvementDialogWidget" maximizable="true">
            <p:ajax event="close" listener="#{mouvementBean.reset}"/>
            <h:form id="viewMouvementForm">
                <ui:include src="/pages/mouvement/mouvementViewInclude.xhtml"/>
                <div style="text-align: center; margin:10px">
                    <p:commandButton value="#{messages.label_close}" styleClass="btn btn-sm btn-danger" icon="ui-icon-close" style="background-color: red;color: white"
                                     onclick="PF('viewMouvementDialogWidget').hide()" type="button"/>
                </div>
            </h:form>
        </p:dialog>

        <p:dialog dynamic="true" id="createAgenceFromEditDialog"
                  rendered="#{mouvementBean.isPermitted('agence:create')}"
                  header="#{messages.dialog_mouvement_create_agence}" modal="true"
                  widgetVar="createAgenceFromEditDialogWidget" maximizable="true">
            <p:ajax event="close" listener="#{agenceBean.reset}"/>
            <p:outputPanel id="createAgencePanel">
                <h:form id="createAgenceForm">
                    <ui:include src="/pages/agence/agenceEditInclude.xhtml">
                        <ui:param name="hideMouvementSelectInput" value="true"/>
                    </ui:include>
                    <div style="text-align: center; margin: 10px">
                        <p:commandButton
                                action="#{mouvementBean.updateAgence(agenceBean.agence)}"
                                value="#{messages.label_save}" icon="ui-icon-disk"
                                actionListener="#{agenceBean.persist}"
                                update=":editMouvementForm:agenceSelectInput :createAgencePanel :growlForm:growl"
                                oncomplete="if(!args.validationFailed) PF('createAgenceFromEditDialogWidget').hide()"/>
                        <p:commandButton value="#{messages.label_close}"
                                         icon="ui-icon-close" style="background-color: red; color: white"
                                         onclick="PF('createAgenceFromEditDialogWidget').hide()"
                                         type="button"/>
                    </div>
                </h:form>
            </p:outputPanel>
        </p:dialog>

    </ui:define>
</ui:composition>
</html>

src/main/webapp/pages/mouvement/mouvementEditInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">
<ui:remove>
    <p:outputPanel styleClass="ui-fluid">

        <p:panelGrid columns="3" columnClasses="ui-grid-col-4,ui-grid-col-6,ui-grid-col-2" layout="grid"
                     style="max-width:400px">
            <h:outputLabel value="#{messages.field_label_mouvement_motif}:" for="motifEditInput"/>
            <p:inputTextarea cols="50" rows="2" value="#{mouvementBean.mouvement.motif}" id="motifEditInput"
                             label="#{messages.field_label_mouvement_motif}"/>
            <p:message for="motifEditInput" display="text"/>

            <h:outputLabel value="#{messages.field_label_mouvement_type}:" for="typeSelect"/>
            <p:selectOneMenu value="#{mouvementBean.mouvement.type}" converter="omnifaces.GenericEnumConverter"
                             id="typeSelect">
                <f:selectItem noSelectionOption="true" itemLabel=""/>
                <f:selectItems value="#{mouvementBean.typeSelectItems}"/>
            </p:selectOneMenu>
            <p:message for="typeSelect" display="text"/>

            <h:outputLabel value="#{messages.field_label_mouvement_user}:" for="userSelectInput"
                           rendered="#{not hideUserSelectInput}"/>
            <h:panelGroup rendered="#{not hideUserSelectInput}">
                <!--                    <p:autoComplete id="userSelectInput" value="#{userQuery}" var="username" itemLabel="#{username}"-->
                <!--                                    itemValue="#{username}" requiredMessage="Ce champ ne peut être vide" placeholder="Nom"-->
                <!--                                    completeMethod="#{mouvementBean.completeUser}" scrollHeight="400">-->
                <!--                        <p:ajax event="itemSelect" listener="#{mouvementBean.onUserSelect}"-->
                <!--                                immediate="true"/>-->
                <!--                    </p:autoComplete>-->

                <p:selectOneMenu value="#{mouvementBean.mouvement.user}"
                                 id="userSelectInput">
                    <f:selectItem noSelectionOption="true" itemLabel=""/>
                    <f:selectItems value="#{mouvementBean.users}"
                                   var="user"
                                   itemLabel="#{user.username}"
                                   itemValue="#{user}"/>
                    <o:converter converterId="omnifaces.SelectItemsConverter" list="#{mouvementBean.users}"/>
                </p:selectOneMenu>
            </h:panelGroup>
            <h:panelGroup rendered="#{not hideUserSelectInput}">

                <p:message for="userSelectInput" display="text" rendered="#{not hideUserSelectInput}"/>
            </h:panelGroup>

        </p:panelGrid>

    </p:outputPanel>
</ui:remove>

<div class="ui-g ui-fluid">
    <div class="ui-g-12 ui-sm-12">
        <h:outputLabel value="#{messages.field_label_mouvement_type}:" for="typeSelect"/>
        <h:selectOneMenu value="#{mouvementBean.mouvement.type}" converter="omnifaces.GenericEnumConverter"
                         styleClass="form-control form-control-border" id="typeSelect">
            <f:selectItem noSelectionOption="true" itemLabel=""/>
            <f:selectItems value="#{mouvementBean.typeSelectItems}"/>
        </h:selectOneMenu>
        <p:message for="typeSelect" display="text"/>
    </div>

    <div class="ui-g-12 ui-sm-12">
        <h:outputLabel value="#{messages.field_label_mouvement_user}:" for="userSelectInput"/>
        <h:selectOneMenu value="#{mouvementBean.mouvement.user}" styleClass="form-control form-control-border"
                         id="userSelectInput">
            <f:selectItem noSelectionOption="true" itemLabel=""/>
            <f:selectItems value="#{mouvementBean.users}"
                           var="user"
                           itemLabel="#{user.username}"
                           itemValue="#{user}"/>
            <o:converter converterId="omnifaces.SelectItemsConverter" list="#{mouvementBean.users}"/>
        </h:selectOneMenu>
        <p:message for="userSelectInput" display="text" rendered="#{not hideUserSelectInput}"/>
    </div>
    <div class="ui-g-12 ui-sm-12">
        <h:outputLabel value="#{messages.field_label_mouvement_visiteur}:" for="visiteurEditInput"/>
        <h:inputText value="#{mouvementBean.mouvement.visiteur}" id="visiteurEditInput" class="form-control form-control-border"
                         label="#{messages.field_label_mouvement_visiteur}"/>
        <p:message for="visiteurEditInput" display="text"/>
    </div>
    <div class="ui-g-12 ui-sm-12">
        <h:outputLabel value="#{messages.field_label_mouvement_motif}:" for="motifEditInput"/>
        <h:inputTextarea cols="50" rows="2" value="#{mouvementBean.mouvement.motif}" id="motifEditInput" styleClass="form-control form-control-border"
                         label="#{messages.field_label_mouvement_motif}"/>
        <p:message for="motifEditInput" display="text"/>
    </div>
</div>


</html>

src/main/webapp/pages/mouvement/mouvementViewInclude.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">

    <p:outputPanel styleClass="ui-fluid" rendered="#{not mouvementBean.isPermitted(mouvementBean.mouvement, 'mouvement:read')}">
        <h:outputText value="#{messages.access_denied}" />
    </p:outputPanel>
    
    <h:panelGrid columns="2" styleClass="dialog" columnClasses="col1,col2" rendered="#{mouvementBean.isPermitted(mouvementBean.mouvement, 'mouvement:read')}">
        
        <h:outputText value="#{messages.field_label_mouvement_date}:" />
        <h:outputText value="#{mouvementBean.mouvement.date}" ><f:convertDateTime pattern="dd/MM/yyyy HH:mm" /></h:outputText>

        <h:outputText value="#{messages.field_label_mouvement_motif}:" />
        <h:outputText value="#{mouvementBean.mouvement.motif}" />

        <h:outputText value="#{messages.field_label_mouvement_type}:" />
        <h:outputText value="#{mouvementBean.getLabelForType(mouvementBean.mouvement.type)}" />

        <h:outputText value="#{messages.field_label_mouvement_user}:" />
        <h:outputText value="#{mouvementBean.mouvement.user.username}" />

        <h:outputText value="#{messages.field_label_mouvement_visiteur}:" />
        <h:outputText value="#{mouvementBean.mouvement.visiteur}" />
    </h:panelGrid>
</html>