src/main/java/cd/forexy/web/security/UserBean.java
package cd.forexy.web.security;

import cd.forexy.domain.AgenceEntity;
import cd.forexy.domain.UserDetailsEntity;
import cd.forexy.domain.security.UserEntity;
import cd.forexy.domain.security.UserGenre;
import cd.forexy.domain.security.UserRole;
import cd.forexy.domain.security.UserStatus;
import cd.forexy.domain.security.UserStatutMarital;
import cd.forexy.service.AgenceService;
import cd.forexy.service.UserDetailsService;
import cd.forexy.service.security.SecurityWrapper;
import cd.forexy.service.security.UserService;
import cd.forexy.web.generic.GenericLazyDataModel;
import cd.forexy.web.util.MessageFactory;

import java.io.Serializable;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;
import javax.persistence.OptimisticLockException;
import javax.persistence.PersistenceException;

import org.primefaces.model.LazyDataModel;

@Named("userBean")
@ViewScoped
public class UserBean implements Serializable {

    private static final Logger logger = Logger.getLogger(UserBean.class.getName());

    private LazyDataModel<UserEntity> lazyModel;

    private static final long serialVersionUID = 1L;

    private UserEntity user;
    private UserEntity connectedUser;

    @Inject
    private UserService userService;

    @Inject
    private UserDetailsService userDetailsService;

    @Inject
    private AgenceService agenceService;

    private List<AgenceEntity> allAgencesList;

    private List<UserDetailsEntity> availableDetailsList;

    public UserEntity getUser() {
        if (user == null) {
            user = new UserEntity();
        }
        return user;
    }

    public void setUser(UserEntity user) {
        this.user = user;
    }

    public void prepareNewUser() {
        this.user = new UserEntity();
        // set any default values now, if you need
    }

    public LazyDataModel<UserEntity> getLazyModel() {
        if (this.lazyModel == null) {
            this.lazyModel = new GenericLazyDataModel<>(userService);
        }
        return this.lazyModel;
    }

    public void persist() {

        String message;

        try {

            if (user.getId() != null) {
                user = userService.update(user);
                message = "message_successfully_updated";
            } else {

                // Check if a user with same username already exists
                if (userService.findUserByUsername(user.getUsername()) != null) {
                    FacesMessage facesMessage = MessageFactory.getMessage(
                            "user_username_exists");
                    facesMessage.setSeverity(FacesMessage.SEVERITY_ERROR);
                    FacesContext.getCurrentInstance().addMessage(null, facesMessage);
                    FacesContext.getCurrentInstance().validationFailed();
                    return;
                }
                // Check if a user with same email already exists            
                if (userService.findUserByEmail(user.getEmail()) != null) {
                    FacesMessage facesMessage = MessageFactory.getMessage(
                            "user_email_exists");
                    facesMessage.setSeverity(FacesMessage.SEVERITY_ERROR);
                    FacesContext.getCurrentInstance().addMessage(null, facesMessage);
                    FacesContext.getCurrentInstance().validationFailed();
                    return;
                }

                user = userService.save(user);
                message = "message_successfully_created";
            }

        } catch (OptimisticLockException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_optimistic_locking_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        } catch (PersistenceException e) {
            logger.log(Level.SEVERE, "Error occured", e);
            message = "message_save_exception";
            // Set validationFailed to keep the dialog open
            FacesContext.getCurrentInstance().validationFailed();
        }

        FacesMessage facesMessage = MessageFactory.getMessage(message,
                "User");
        FacesContext.getCurrentInstance().addMessage(null, facesMessage);
    }

    public String delete() {
        userService.delete(user);
        FacesMessage facesMessage = MessageFactory.getMessage(
                "message_successfully_deleted", "User");
        FacesContext.getCurrentInstance().addMessage(null, facesMessage);
        reset();
        return null;
    }

    public void reset() {
        user = null;

        allAgencesList = null;

        availableDetailsList = null;

    }

    public SelectItem[] getRolesSelectItems() {
        SelectItem[] items = new SelectItem[UserRole.values().length];

        int i = 0;
        for (UserRole role : UserRole.values()) {
            String label = MessageFactory.getMessageString(
                    "enumeration_label_user_roles_" + role.toString());
            items[i++] = new SelectItem(role, label == null ? role.toString() : label);
        }
        return items;
    }

    public SelectItem[] getStatusSelectItems() {
        SelectItem[] items = new SelectItem[UserStatus.values().length];

        int i = 0;
        for (UserStatus status : UserStatus.values()) {
            items[i++] = new SelectItem(status, status.toString());
        }
        return items;
    }

    // Get a List of all agence
    public List<AgenceEntity> getAgences() {
        if (this.allAgencesList == null) {
            this.allAgencesList = agenceService.findAllAgenceEntities();
        }
        return this.allAgencesList;
    }

    // Update agence of the current user
    public void updateAgence(AgenceEntity agence) {
        this.user.setAgence(agence);
        // Maybe we just created and assigned a new agence. So reset the allAgenceList.
        allAgencesList = null;
    }

    // Get a List of all details
    public List<UserDetailsEntity> getAvailableDetails() {
        if (this.availableDetailsList == null) {
            this.availableDetailsList = userDetailsService.findAvailableDetails(this.user);
        }
        return this.availableDetailsList;
    }

    // Update details of the current user
    public void updateDetails(UserDetailsEntity userDetails) {
        this.user.setDetails(userDetails);
        // Maybe we just created and assigned a new details. So reset the availableDetailsList.
        availableDetailsList = null;
    }

    public SelectItem[] getGenreSelectItems() {
        SelectItem[] items = new SelectItem[UserGenre.values().length];

        int i = 0;
        for (UserGenre genre : UserGenre.values()) {
            items[i++] = new SelectItem(genre, getLabelForGenre(genre));
        }
        return items;
    }

    public String getLabelForGenre(UserGenre value) {
        if (value == null) {
            return "";
        }
        String label = MessageFactory.getMessageString(
                "enum_label_user_genre_" + value);
        return label == null ? value.toString() : label;
    }

    public SelectItem[] getStatutMaritalSelectItems() {
        SelectItem[] items = new SelectItem[UserStatutMarital.values().length];

        int i = 0;
        for (UserStatutMarital statutMarital : UserStatutMarital.values()) {
            items[i++] = new SelectItem(statutMarital, getLabelForStatutMarital(statutMarital));
        }
        return items;
    }

    public String getLabelForStatutMarital(UserStatutMarital value) {
        if (value == null) {
            return "";
        }
        String label = MessageFactory.getMessageString(
                "enum_label_user_statutMarital_" + value);
        return label == null ? value.toString() : label;
    }

    public void loadCurrentUser() {
        String username = SecurityWrapper.getUsername();
        if (username != null) {
            this.user = this.userService.findUserByUsername(username);
        } else {
            throw new RuntimeException("Can not get authorized user name");
        }
    }

    public boolean isPermitted(String permission) {
        return SecurityWrapper.isPermitted(permission);
    }

    public UserEntity getConnectedUser() {
        String username = SecurityWrapper.getUsername();
        if (username != null) {
            this.connectedUser = userService.findUserByUsername(username);
        }
        return connectedUser;
    }

    public long countAllUsers() {
        return userService.countAllEntries();
    }
}

src/main/webapp/pages/webapp/pages/user/activation.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
<ui:composition template="/templates/layout.xhtml">
    <ui:define name="content">
        <h:form prependId="false">
            <p:panel>
                <h:outputText value="#{messages.activation_success}" rendered="#{userActivationBean.valid}"/>
                <h:outputText value="#{messages.activation_fail}" rendered="#{!userActivationBean.valid}"/>
            </p:panel>
        </h:form>
    </ui:define>

</ui:composition>
</html>

src/main/webapp/pages/webapp/pages/user/changePassword.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui">
<ui:composition template="/templates/template.xhtml">
    <ui:define name="content">
        <h:form id="form1">
            <p:messages id="messages" showDetail="false" autoUpdate="true" closable="false"/>
        </h:form>

        <h:form prependId="false">
            <h:panelGroup rendered="#{! userChangePasswordBean.successpwdchange}">
                <p:panel rendered="#{!userChangePasswordBean.valid}">
                    <h4><h:outputText value="#{messages.profile_page_password_change}"/></h4>
                    <p:panelGrid columns="3">
                        <h:outputText value="#{messages.registration_new_password}:"/>
                        <p:password value="#{userChangePasswordBean.new_password}" id="passwordEditInput"
                                    required="true" match="passwordRepeatEditInput"
                                    label="#{messages.registration_new_password}"/>
                        <p:message for="passwordEditInput" display="icon"/>

                        <h:outputText value="#{messages.registration_new_password_repeat}:"/>
                        <p:password value="#{userChangePasswordBean.new_password_repeat}" id="passwordRepeatEditInput"
                                    required="true"
                                    label="#{messages.registration_new_password_repeat}"/>
                        <p:message for="passwordRepeatEditInput" display="icon"/>

                        <f:facet name="footer">
                            <p:commandButton ajax="false" action="#{userChangePasswordBean.changePassword}"
                                             value="#{messages.change_password_submit}"/>
                        </f:facet>
                    </p:panelGrid>
                </p:panel>
            </h:panelGroup>
            <h:panelGroup rendered="#{userChangePasswordBean.successpwdchange}">


                <p:tab id="OrderStatus">
                    <div style="height: 80%">
                        <div style="text-align: center;">
                            <p:graphicImage style="width: 15%;" library="images" name="check.png"/>
                            <p>
                                Password successfuly changed <br/>
                                Please login with your new credentials.
                            </p>
                            <h:outputLink class="fa fa-home btn btn btn-primary" style="margin-bottom: 5%"
                                          value="#{userChangePasswordBean.baseURL}/">Login page</h:outputLink>
                        </div>
                    </div>
                </p:tab>


            </h:panelGroup>

            <!--        <p:panel rendered="#{!userChangePasswordBean.valid}">-->
            <!--            <h:outputText value="#{messages.url_not_valid}" />-->
            <!--        </p:panel>-->
        </h:form>
    </ui:define>

</ui:composition>
</html>

src/main/webapp/pages/webapp/pages/user/profileOld.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">
<ui:composition template="/templates/template.xhtml">

<ui:define name="content">

  <f:view>
        <f:event type="preRenderView" listener="#{userBean.loadCurrentUser()}"/>
  </f:view>

  <h:form id="form1">
    <p:messages id="messages" showDetail="false" autoUpdate="true" closable="false" />
  </h:form>
  
    <p:panel>
      <h3><h:outputText value="#{messages.profile_page}" /></h3>
      
      <h4><h:outputText value="#{messages.profile_my_data}" /></h4>
        
      <h:form prependId="false">
      <p:panel id="userEditPanel">
          
            <h:panelGrid columns="3" styleClass="dialog" columnClasses="col1,col2,col3">
              <h:outputText value="#{messages.field_label_user_username}:" />
              <h:outputText value="#{userBean.user.username}" />
              <h:outputText value="" />

              <h:outputText value="#{messages.field_label_user_email}:" />
              <h:outputText value="#{userBean.user.email}" />
              <h:outputText value="" />
    
              <h:outputText value="#{messages.field_label_user_roles}:" />
              <p:outputPanel>
                <ui:repeat value="#{userBean.user.roles}" var="role">
                    <h:outputText value="#{role}" /><br/>
                </ui:repeat>
              </p:outputPanel>
              <h:outputText value="" />
              
                <h:outputLabel value="#{messages.field_label_user_details}:" for="detailsSelectInput" rendered="#{not hideDetailsSelectInput}"/>
                <h:panelGroup rendered="#{not hideDetailsSelectInput}">
                    <p:selectOneMenu value="#{userBean.user.details}"
                                    id="detailsSelectInput">
                        <f:selectItem noSelectionOption="true" itemLabel="" />
                        <f:selectItems value="#{userBean.availableDetails}" 
                                    var="userDetails" 
                                    itemLabel="#{userDetails.id}"
                                    itemValue="#{userDetails}" />
                        <o:converter converterId="omnifaces.SelectItemsConverter" list="#{userBean.availableDetails}" />
                    </p:selectOneMenu>
                </h:panelGroup>
                <h:panelGroup rendered="#{not hideDetailsSelectInput}">
                
                    <p:commandButton icon="ui-icon-plusthick" title="#{messages.label_create}"
                              action="#{userDetailsBean.prepareNewUserDetails()}"
                              update=":createDetailsFromEditDialog"
                              resetValues="true"
                              oncomplete="PF('createDetailsFromEditDialogWidget').show()"
                              rendered="#{applicationBean.componentExists('createDetailsFromEditDialog') and userBean.isPermitted('userDetails:create')}"
                              style="vertical-align:top;" partialSubmit="true" process="@this">
                    </p:commandButton>
                    
                    <p:message for="detailsSelectInput" display="icon" rendered="#{not hideDetailsSelectInput}"/>
                </h:panelGroup>
                
                <h:outputLabel value="#{messages.field_label_user_telephone}:" for="telephoneEditInput" />
                <p:inputText value="#{userBean.user.telephone}" id="telephoneEditInput" 
                    label="#{messages.field_label_user_telephone}" />
                <p:message for="telephoneEditInput" display="icon" />

                <h:outputLabel value="#{messages.field_label_user_adresse}:" for="adresseEditInput" />
                <p:inputText value="#{userBean.user.adresse}" id="adresseEditInput" 
                    label="#{messages.field_label_user_adresse}" />
                <p:message for="adresseEditInput" display="icon" />

                <h:outputLabel value="#{messages.field_label_user_genre}:" for="genreSelect" />
                <p:selectOneMenu value="#{userBean.user.genre}" converter="omnifaces.GenericEnumConverter"  id="genreSelect">
                    <f:selectItem noSelectionOption="true" itemLabel="" />
                    <f:selectItems value="#{userBean.genreSelectItems}" />
                </p:selectOneMenu>
                <p:message for="genreSelect" display="icon" />

                <h:outputLabel value="#{messages.field_label_user_statutMarital}:" for="statutMaritalSelect" />
                <p:selectOneMenu value="#{userBean.user.statutMarital}" converter="omnifaces.GenericEnumConverter"  id="statutMaritalSelect">
                    <f:selectItem noSelectionOption="true" itemLabel="" />
                    <f:selectItems value="#{userBean.statutMaritalSelectItems}" />
                </p:selectOneMenu>
                <p:message for="statutMaritalSelect" display="icon" />

                <h:outputLabel value="#{messages.field_label_user_agence}:" for="agenceSelectInput" rendered="#{not hideAgenceSelectInput}"/>
                <h:panelGroup rendered="#{not hideAgenceSelectInput}">
                    <p:selectOneMenu value="#{userBean.user.agence}"
                                    id="agenceSelectInput">
                        <f:selectItem noSelectionOption="true" itemLabel="" />
                        <f:selectItems value="#{userBean.agences}" 
                                    var="agence" 
                                    itemLabel="#{agence.agenceID}"
                                    itemValue="#{agence}" />
                        <o:converter converterId="omnifaces.SelectItemsConverter" list="#{userBean.agences}" />
                    </p:selectOneMenu>
                </h:panelGroup>
                <h:panelGroup rendered="#{not hideAgenceSelectInput}">
                
                    <p:commandButton icon="ui-icon-plusthick" title="#{messages.label_create}"
                              action="#{agenceBean.prepareNewAgence()}"
                              update=":createAgenceFromEditDialog"
                              resetValues="true"
                              oncomplete="PF('createAgenceFromEditDialogWidget').show()"
                              rendered="#{applicationBean.componentExists('createAgenceFromEditDialog') and userBean.isPermitted('agence:create')}"
                              style="vertical-align:top;" partialSubmit="true" process="@this">
                    </p:commandButton>
                    
                    <p:message for="agenceSelectInput" display="icon" rendered="#{not hideAgenceSelectInput}"/>
                </h:panelGroup>
                
              </h:panelGrid>
              
              <div>
                <p:commandButton value="#{messages.user_profile_submit}"
                    icon="ui-icon-disk" action="#{userBean.persist}"
                    update=":userEditPanel :growlForm:growl" />
                <p:commandButton action="#{userProfileBean.cancel}" value="#{messages.label_cancel}" immediate="true" />
              </div>

      </p:panel>
      </h:form>

      <h4><h:outputText value="#{messages.profile_page_password_change}" /></h4>
        
      <h:form prependId="false">
      <p:panel>
      <h:panelGrid columns="3" styleClass="dialog" columnClasses="col1,col2,col3">

        <h:outputText value="#{messages.user_profile_old_password}:" />
        <p:password value="#{userProfileBean.old_password}" id="passwordOldInput" required="true"
                      label="#{messages.user_profile_old_password}" />
        <p:message for="passwordOldInput" display="icon" />

        <h:outputText value="#{messages.user_profile_new_password}:" />
        <p:password value="#{userProfileBean.new_password}" id="passwordEditInput" required="true" match="passwordRepeatEditInput"
              label="#{messages.user_profile_new_password}" />
        <p:message for="passwordEditInput" display="icon" />
     
        <h:outputText value="#{messages.user_profile_new_password_repeat}:" />
        <p:password value="#{userProfileBean.new_password_repeat}" id="passwordRepeatEditInput" required="true"
              label="#{messages.user_profile_new_password_repeat}" />
        <p:message for="passwordRepeatEditInput" display="icon" />

      </h:panelGrid>
      
      <div>
        <p:commandButton action="#{userProfileBean.update}" value="#{messages.user_profile_submit}" icon="ui-icon-disk" />
        <p:commandButton action="#{userProfileBean.cancel}" value="#{messages.label_cancel}" immediate="true" />
      </div>
      
      </p:panel>
      </h:form>
      
    </p:panel>

</ui:define>
</ui:composition>
</html>

src/main/webapp/pages/webapp/pages/user/register.xhtml
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:o="http://omnifaces.org/ui">
<ui:composition template="/templates/layout.xhtml">

<ui:define name="content">

  <!--  Email sending may be slow, so show waiting animation to prevent user from sending twice -->
  <p:ajaxStatus onstart="PF('statusDialog').show()" onsuccess="PF('statusDialog').hide()" />
  <p:dialog widgetVar="statusDialog" modal="true" draggable="false" closable="false" resizable="false" showHeader="false">
      <p:graphicImage name="images/waiting.gif" alt="loading..." />
  </p:dialog>

  <h:form id="form1">
    <p:messages id="messages" showDetail="false" autoUpdate="true" closable="false" />
  </h:form>
  
  <h:form prependId="false">
    <p:panel>
      <h3><h:outputText value="#{messages.please_register}" /></h3>
      
      <o:validateEqual components="emailEditInput emailRepeatEditInput"
              showMessageFor="emailRepeatEditInput" message="#{messages.user_email_different_input}"/>
      
      <p:panelGrid columns="3">
        <h:outputLabel for="usernameInput" value="#{messages.registration_username}:" />
        <p:inputText id="usernameInput" required="true"
            value="#{userRegistrationBean.user.username}" label="#{messages.registration_username}">
        </p:inputText>
        <p:message for="usernameInput" display="icon" />
           
        <h:outputLabel value="#{messages.registration_password}:" for="passwordEditInput" />
        <p:password value="#{userRegistrationBean.user.password}" id="passwordEditInput" required="true"
             match="passwordRepeatEditInput" label="#{messages.registration_password}" />
        <p:message for="passwordEditInput" display="icon" />
     
        <h:outputLabel value="#{messages.registration_password_repeat}:" for="passwordRepeatEditInput" />
        <p:password value="#{userRegistrationBean.user.password}" id="passwordRepeatEditInput" required="true"
              label="#{messages.registration_password_repeat}" />
        <p:message for="passwordRepeatEditInput" display="icon" />
     
        <h:outputLabel value="#{messages.registration_email}:" for="emailEditInput" />
        <p:inputText value="#{userRegistrationBean.user.email}" id="emailEditInput"
              label="#{messages.registration_email}" />
        <p:message for="passwordEditInput" display="icon" />
     
        <h:outputLabel value="#{messages.registration_email_repeat}:" for="emailRepeatEditInput" />
        <p:inputText value="#{userRegistrationBean.user.email}" id="emailRepeatEditInput"
                label="#{messages.registration_email_repeat}" />
        <p:message for="emailRepeatEditInput" display="icon" />

                <h:outputLabel value="#{messages.field_label_user_details}:" for="detailsSelectInput" rendered="#{not hideDetailsSelectInput}"/>
                <h:panelGroup rendered="#{not hideDetailsSelectInput}">
                    <p:selectOneMenu value="#{userBean.user.details}"
                                    id="detailsSelectInput">
                        <f:selectItem noSelectionOption="true" itemLabel="" />
                        <f:selectItems value="#{userBean.availableDetails}" 
                                    var="userDetails" 
                                    itemLabel="#{userDetails.id}"
                                    itemValue="#{userDetails}" />
                        <o:converter converterId="omnifaces.SelectItemsConverter" list="#{userBean.availableDetails}" />
                    </p:selectOneMenu>
                </h:panelGroup>
                <h:panelGroup rendered="#{not hideDetailsSelectInput}">
                
                    <p:message for="detailsSelectInput" display="icon" rendered="#{not hideDetailsSelectInput}"/>
                </h:panelGroup>
                
                <h:outputLabel value="#{messages.field_label_user_telephone}:" for="telephoneEditInput" />
                <p:inputText value="#{userBean.user.telephone}" id="telephoneEditInput" 
                    label="#{messages.field_label_user_telephone}" />
                <p:message for="telephoneEditInput" display="icon" />

                <h:outputLabel value="#{messages.field_label_user_adresse}:" for="adresseEditInput" />
                <p:inputText value="#{userBean.user.adresse}" id="adresseEditInput" 
                    label="#{messages.field_label_user_adresse}" />
                <p:message for="adresseEditInput" display="icon" />

                <h:outputLabel value="#{messages.field_label_user_genre}:" for="genreSelect" />
                <p:selectOneMenu value="#{userBean.user.genre}" converter="omnifaces.GenericEnumConverter"  id="genreSelect">
                    <f:selectItem noSelectionOption="true" itemLabel="" />
                    <f:selectItems value="#{userBean.genreSelectItems}" />
                </p:selectOneMenu>
                <p:message for="genreSelect" display="icon" />

                <h:outputLabel value="#{messages.field_label_user_statutMarital}:" for="statutMaritalSelect" />
                <p:selectOneMenu value="#{userBean.user.statutMarital}" converter="omnifaces.GenericEnumConverter"  id="statutMaritalSelect">
                    <f:selectItem noSelectionOption="true" itemLabel="" />
                    <f:selectItems value="#{userBean.statutMaritalSelectItems}" />
                </p:selectOneMenu>
                <p:message for="statutMaritalSelect" display="icon" />

                <h:outputLabel value="#{messages.field_label_user_agence}:" for="agenceSelectInput" rendered="#{not hideAgenceSelectInput}"/>
                <h:panelGroup rendered="#{not hideAgenceSelectInput}">
                    <p:selectOneMenu value="#{userBean.user.agence}"
                                    id="agenceSelectInput">
                        <f:selectItem noSelectionOption="true" itemLabel="" />
                        <f:selectItems value="#{userBean.agences}" 
                                    var="agence" 
                                    itemLabel="#{agence.agenceID}"
                                    itemValue="#{agence}" />
                        <o:converter converterId="omnifaces.SelectItemsConverter" list="#{userBean.agences}" />
                    </p:selectOneMenu>
                </h:panelGroup>
                <h:panelGroup rendered="#{not hideAgenceSelectInput}">
                
                    <p:message for="agenceSelectInput" display="icon" rendered="#{not hideAgenceSelectInput}"/>
                </h:panelGroup>
                
        <f:facet name="footer">
            <p:commandButton action="#{userRegistrationBean.register}" value="#{messages.registration_submit}"/>
        </f:facet>
      </p:panelGrid>
    </p:panel>

  </h:form>

</ui:define>
</ui:composition>
</html>